### ISSUE TITLE
Content Wizard - publish menu is not visible in mobile resolution

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1142]
1. Change browser window size to a  mobile resolution.
2. Open a content(Work in Progress).

Issues : 
 - publish menu is not available in the wizard.
 -  Default Action is not present in the toolbar.

![image](https://user-images.githubusercontent.com/3728712/67942406-cce42900-fbe8-11e9-8b3d-1d3cf419b9be.png)

**Comment by alansemenov** [comment]
When content is in "in progress" workflow state, the default action at the bottom of the screen should be "Mark as Ready" instead of "Publish":

![image](https://user-images.githubusercontent.com/11612490/69066225-3b1a4f80-0a21-11ea-9b6d-33373d3fbf06.png)

The workflow state icon should have the dropdown menu toggler (it's already in DOM but hidden) which will expand the dropdown menu:

![image](https://user-images.githubusercontent.com/11612490/69066552-c4ca1d00-0a21-11ea-8145-9dbbe2bdda8f.png)
