### ISSUE TITLE
Page template config is not shown in the Inspect panel of supported content

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1175]
1. default template has the config:

```
    <form>
        <input type="TextLine" name="title">
            <label>Title</label>
            <occurrences minimum="0" maximum="1"/>
        </input>
    </form>
```
2. Create a site, then add new template ( select  `article` in support selector );

![image](https://user-images.githubusercontent.com/3728712/68661525-271bad00-054c-11ea-9463-155affca27f7.png)

3. Open new article-wizard.

![image](https://user-images.githubusercontent.com/3728712/68661356-e3c13e80-054b-11ea-9ba5-35e257d91c50.png)

**Issue Template config is not shown in supported content**

**Comment by alansemenov** [comment]
This is by (current) design (see https://github.com/enonic/app-contentstudio/issues/1062). We don't show config from the template inside content because user cannot override template config on content level. It's very confusing if user sees config from the template, tries to change it but changes don't get saved, that's why we don't show it. The best would be to show config from the template but disable the controls inside, but that's a different issue.
