### ISSUE TITLE
New project doesn't show up in the Settings grid after save

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1627]
**Case 1**
1. Navigate to Settings panel, expand Projects folder.
2. Open new project wizard and save a project

Bug: Grid is not refreshed: - new project does not appear in the panel (This case does not always reproduce)

![image](https://user-images.githubusercontent.com/3728712/77150651-62535d00-6aa5-11ea-9624-829f6affe1b6.png)

**Case 2** (this case always reproduces the bug)

- Open new wizard type a name and save it.
- do not close the wizard, click on `Home` button
**Bug - new project is not present in grid**

**Comment by ashklianko** [comment]
After receiving Project server event we first wait some static time before firing ui event to let backend process it's data, however this delay in rare cases is not enough, so fetching list of projects returns stale data. 
There's not much we can do with that on frontend except manipulating delay time or keep sending list requests until required data received, however that might not be optimal solution since this is reproduced on rare occasions and doesn't lead to errors on ui. 
@vbradnitski , is there anything to do on backend with that?
Paying attention that same delay is used for Principal events

**Comment by sigdestad** [comment]
Hmm.. Shouldn't we have a specific event for when a project is created, updated and deleted?

**Comment by ashklianko** [comment]
We do, events are sent via web socket on node creation immediately, and in case of create we know that node with 'some' id was created, but if I am not mistaken node needs some time to be indexed or whatever before fetch will return it. Please correct me if I am wrong

**Comment by vbradnitski** [comment]
There can be two source of the problem:
1- RefreshCommand wasn't called in repositoryService for create operation.
2- Roles weren't created for new project in time.
I'll check.

**Comment by vbradnitski** [comment]
can't be reproduced in master for now, but have to wait new project create/update changes in epic-project-language branch.
