### ISSUE TITLE
Site Wizard - 'Save' button gets enabled after version rollback

### ISSUE THREAD

**Issue by jsi** [enonic/app-contentstudio#22]
@sgauruseu commented on [Thu Oct 11 2018](https://github.com/enonic/app-contentstudio-old/issues/481)

1. Open new site-wizard, type a name and save it 
2. Select `Features` in  the wizard and save it 

![image](https://user-images.githubusercontent.com/3728712/46796071-5f065e80-cd54-11e8-8dde-455fd94d6f94.png)

3. Open Version history panel and rollback the version, when application is not selected yet.

Bug:  `Save` button is getting enabled, 'Save Before Close' dialog appears, when try to close the wizard

![image](https://user-images.githubusercontent.com/3728712/46796193-b278ac80-cd54-11e8-8972-b96469dc2e8d.png)

**Comment by alansemenov** [comment]
It's not just rollback to a version without application. Seems like Save button gets enabled after any version rollback. Just try this:
1. Open fresh Features site
2. Add an image component, select an image. Content gets autosaved - Save is disabled.
3. Repeat previous step again (so that there are 2 image components). Save is disabled.
4. Rollback to previous version. Everything is correct but Save becomes enabled.

**Comment by ashklianko** [comment]
Added fix into https://github.com/enonic/app-contentstudio/issues/301 because closely related
