### ISSUE TITLE
Media content should not be auto-downloaded on preview

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2382]
1. Upload a `*.avi` file 
2. Click on the item in grid.

BUG: Save as modal dialog opens after clicking on `*.avi` item

![image](https://user-images.githubusercontent.com/3728712/96242092-be368380-0fab-11eb-8ca8-6446e5f12b09.png)

This issue does not reproduce with `*.mp4, *.mts`  files

**Comment by ashklianko** [comment]
This is a native browser behaviour when iframe doesn't know how to render item that was set in `src` attribute, in this case this is a content with `video/avi` mime type. `MediaAllowsPreviewRequest ` returns `true` for it since `video/avi` is in list of allowed preview types, and we could only add some exceptions for allowed preview types on backend, because on frontent for content object we only keep our internal type like `media:image` and don't know actual mime type. @alansemenov should we reject this issue or continue with it on backend?
