### ISSUE TITLE
Incorrect behaviour of Context Panel switching between floating and docked mode

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#2563]
We have a threshold of around 1480px width when the Context panel (the one with widgets) switches between floating and docked mode. 

This seems to work fine in the Content grid, but not in the Page Editor. If you open the Page editor in a browser window that is 1480px wide, the Context panel will still be in the floating mode.

It seems that in the Editor we are expecting the width of the **editor panel**, not the entire window, to be >=1480px for the docked mode to kick in, because when you collapse the form panel on the left side then the Context panel will correctly switch from the floating mode to the docked mode.

**Comment by sigdestad** [comment]
Hmm.. I think this is a slightly wrong description of the problem.

Basically, on my Mac with 1440px resolution, opening the content editor is fine. The widget panel is floating over the page(due to limiated space). However, the problem comes when I go into page editor mode (click on page, or click customize), the wizard panel used to collapse. This again causes page editor to maximize, and dock the widget panel.

So, the problem is essentially that I now have to manually press "collapse wizard panel" when going into the page editor.
Try rolling back to pre CS 3.0 and see how things were working there in 1440px resolution.

**Comment by alansemenov** [comment]
Here's how it works on Nightly with the latest snapshot. My browser window is 1280px wide. Exactly the same behaviour on enonic.com/admin. As you can see, the wizard panel collapses and the widget panel goes into the docked mode.

![ezgif-2-fd8403eb0f90](https://user-images.githubusercontent.com/11612490/100227050-d5f51600-2f20-11eb-8738-991ef44ba4df.gif)

**Comment by sigdestad** [comment]
So, this looks like how it should behave, but the breaking points must have changed? It should work like this even for 1440px resolution...

**Comment by sigdestad** [comment]
Also, you don't even have to update the widget panel, just clicking in page editor should give this effect and open widget panel in the same go!

**Comment by alansemenov** [comment]
It seems to work fine now
