### ISSUE TITLE
Open the last used project by default

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#3075]
When user has access to several projects he has to select one every time he logs in. This can become annoying if you mostly work with one project, so it will be convenient if Content Studio remembered the last project you worked in.

![image](https://user-images.githubusercontent.com/11612490/116087572-47d4b580-a6a1-11eb-89c1-adbe1f9781a5.png)

1. Store id of the project selected in the "Select project" dialog in browser's [local storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage). Make sure we always store just one value, so overwrite it on every selection. Call the key `contentstudio:defaultProject`.
2. If `contentstudio:defaultProject` has a value and user has access to this project, redirect to this project without opening the "Select Project" dialog.
3. If `contentstudio:defaultProject` doesn't have a value or project doesn't exist or user doesn't have access to it, use the current behaviour.
4. Whenever a project is deleted, delete the entry from the local storage if it's set to the deleted project Id.
5. If upon logging in it turns out that projectId from `contentstudio:defaultProject` doesn't exist (f.ex. when another user deleted it), delete the entry from the local storage.

**Comment by ashklianko** [comment]
Will slightly update logic: there's no need to track deleted items because whenever you choose/change project it will rewrite value in localStorage. Thus will do next on opening studio: 
1) If studio is opened with project name in path - will try to open mentioned project if it is available, otherwise will show project selection dialog and after selection localStorage project gets rewritten
2) If no project present in studio url when opening it then same logic applies as in 1) - trying to open project from localStorage if available and if not it will be rewritten after choosing project in selection dialog
