### ISSUE TITLE
Incorrect status after version rollback of a content scheduled for publishing

### ISSUE THREAD

**Issue by jsi** [enonic/app-contentstudio#31]
@sgauruseu commented on [Thu Nov 22 2018](https://github.com/enonic/app-contentstudio-old/issues/564)

1. Create a folder and  click on Publish button and `Schedule` it in future(Do not close the wizard)

![image](https://user-images.githubusercontent.com/3728712/48902351-5fbd0500-ee69-11e8-8b50-df769195dd18.png)

2. Change the content (add a language). Save it  (Content is `Modified Pending`)
3.  Unpublish this content in wizard
4. Rollback the previous version .

**Bug**:  Status is getting 'Unpublished Pending'

![image](https://user-images.githubusercontent.com/3728712/48902558-f8ec1b80-ee69-11e8-9af5-80f414cf5350.png)

5. Publish the content again
Expected - status is "Published"
Actual - status is `Published Pending`

**Comment by alansemenov** [comment]
The bug here is not what's described. After we unpublish the content (step 3), it's no longer pending anything. So after rollback of the version in step 4, the status should remain unpublished and content should be changed to what it was before the change in step 2 (no language selected).

So, expected after step 5 is: status "Unpublished", content with no language selected.
