### ISSUE TITLE
Details  Panel should be reset to min width when it switches from the docked to the floating mode.

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3270]
Set browser window size  width about 2000, or set Full window mode for the browser (monitor 24'')
1) Open an existing site .

**Issue 1** : Whether it is necessary to switch from docked to floating mode if there is enough width in the browser window?
**Issue 2** : Details Panel  switches from docked to floating mode immediately after opening the site and width should be reset to min width.
![image](https://user-images.githubusercontent.com/3728712/123781981-82471280-d8dd-11eb-8cd8-bc73ee5650a9.png)

**Comment by alansemenov** [comment]
@sgauruseu what width is your browser window? It's not an issue that the panel overlaps the toolbar or the selector - you can always collapse the form on the left or make the details panel more narrow - the issue is that the width of the details panel should be reset to min width when it switches from the docked to the floating mode.

**Comment by sgauruseu** [comment]
@alansemenov  browser.width=1970

**Comment by alansemenov** [comment]
@ashklianko I also experienced several times that context panel opens in a docked mode while it should've been in floating. Usually happens inside the content wizard, after collapsing the content form on the left side. Should be investigated...
