### ISSUE TITLE
Incorrect behaviour of filtering in Browse Panel

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3430]
1. Open `Filter Panel` and type the `features`

**Issue - 3 items are filtered.** (Actually Features site has 4 templates )
![image](https://user-images.githubusercontent.com/3728712/130054250-1f3562d1-cb11-47b7-932a-063715f4c8e5.png)

2. Open `Features` site and click on `Save as Template` menu item (main region is selected)

![image](https://user-images.githubusercontent.com/3728712/130054725-96c36100-e031-48f4-9cf2-c5d6901c86cc.png)

3. Go to the browse panel 

**Issue - 4 items are filtered in the grid**

![image](https://user-images.githubusercontent.com/3728712/130054994-c513c6dd-a5aa-4cf9-a44c-16f1bb7b1ef7.png)

**Comment by ashklianko** [comment]
Checked why some items are shown on filtering and why some are not.
Our search query is searching for a fulltext and ngram results on 3 fields: `displayName`,`_name`,`_alltext` where the latest is a system generated property containing indexed string values of a content [_alltext](https://developer.enonic.com/docs/xp/stable/storage/indexing#_allText)
Our predefined Features templates like _Default_ or _Reference_ are having data where property value contains 'features' entry:
![image](https://user-images.githubusercontent.com/4255706/163997442-d19a4732-8059-49a6-96cd-7cd7e5a04839.png)
That results in a property:
![image](https://user-images.githubusercontent.com/4255706/163997513-0830b725-7d53-4473-96bb-995d15229d76.png)
Thus these templates are returned as a query search result and that's why others are don't until you add some property containing 'features' token.
@alansemenov , I think I can close it
