### ISSUE TITLE
Incorrect style of tooltips

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3771]
1. Select Features and open wizard for `Set In Set` content.
2. Click on `Add contact info` button
3. Collapse the just added form,  `Click to expand` - tooltips appears after the click(OK)

**BUG** - The tooltip (Click to expand) has incorrect style

**Comment by alansemenov** [comment]
Examples of incorrect tooltips (native instead of custom):
![image](https://user-images.githubusercontent.com/11612490/140897103-e7775089-52c0-4b2e-abe0-86977e6131c7.png)
![image](https://user-images.githubusercontent.com/11612490/140897131-f7094d5b-8b7e-438e-a42f-d2601a8748d7.png)
![image](https://user-images.githubusercontent.com/11612490/140897263-69521e2b-0d6b-4239-b837-6883fc8643f9.png)

Correct tooltips on the same page:
![image](https://user-images.githubusercontent.com/11612490/140897295-9dc8d556-be75-4769-8ade-e297584b1153.png)
![image](https://user-images.githubusercontent.com/11612490/140897349-ef1518ca-7c8a-45d3-8ef8-d7f35f1d34ed.png)
