### ISSUE TITLE
Replace _blank.html with a static div

### ISSUE THREAD

**Issue by rymsha** [enonic/app-contentstudio#4088]
As per
https://github.com/enonic/xp/issues/8642#issuecomment-1008811981
CKEditor won't be able to load _blank. Instead it can be a different url - pointing to controller that overrides `X-Frame-Options` header to  `SAMEORIGIN`

One extra benefit of using controller instead of static html - it can be i18ed

**Comment by alansemenov** [comment]
@ashklianko We should probably get rid of `_blank.html` altogether, instead of playing with headers. I don't remember why it was added, but it should be a simple div with localised text that we show when there are no controllers.

![image](https://user-images.githubusercontent.com/11612490/149304971-ad14a989-a7f7-4b02-9eeb-d5d2aa65132a.png)
