### ISSUE TITLE
NOTICE.txt seems broken

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-contentstudio#4188]
This can not possibly be a complete list of all OS libraries used by CS?
Also, the license texts below seems very strange and messy - this file looks very tidy and correct for XP repo.

Please update so file is complete with all dependencies, and nicely formatted.

**Comment by jsi** [comment]
Not sure how to do this properly.

The only thing in CS that is not in XP is CK Editor.  So to get a complete list of all dependencies, we can simply copy XP and add CK Editor, but is that how we should do it?  CS only runs on XP, so by saying XP is required and licenses are inherited, listing only CK Editor is correct.

**Comment by sigdestad** [comment]
No, you need to list compile-time dependencies of what is being used in this app, XP is just one of these

**Comment by jsi** [comment]
Well, as far as I can tell, there are three compile-time dependencies: Apache Commons Text, XP (multiple libs) and lib-admin-ui, and then the CK Editor is bundled.

I don't think there are any others, but maybe @alansemenov can answer this?

Since all the code internally to XP is hidden behind the API, I do not think these should be listed in NOTICE.txt, so the only question I have (unless there are more dependencies), is if we should list XP and lib-admin-ui?

**Comment by sigdestad** [comment]
I guess the lib-admin-ui should be listed, XP is not needed due to linking exception - and the fact that it is an XP app anyway.

**Comment by sigdestad** [comment]
Surprised if there are not more - is lib-admin-ui doing everything??
