### ISSUE TITLE
Title is not correctly updated after  saving a content  in FF

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#4511]
ENVIRONMENT - Windows , FF

1, Open CS with `FF` browser.
2. Open new wizard for folder. Fill in the name input and click on `Save` button

**BUG** -  The display name of the content is not present in the tab title after saving this content:
![image](https://user-images.githubusercontent.com/3728712/165906328-86532431-c3bd-4dc5-8f05-21cfceb53710.png)

3. Reopen this content iin FF,  expected title appears in the tab title 

![image](https://user-images.githubusercontent.com/3728712/165906741-828e9f67-e2dd-4a6c-8806-98ba06d8e2d9.png)

**Comment by alansemenov** [comment]
Also, for a new content it should say "_New content / Home_" instead of "_/ Home_".

**Comment by ashklianko** [comment]
Also unclear why in Chrome we have <name> / Content Studio and in FF we have <name> / Home. Will check

**Comment by alansemenov** [comment]
> Also, for a new content it should say "New content / Home" instead of "/ Home".

Correction to this. It seems to work correctly in both Chrome and FF, showing "`Unnamed <content-type> / `" for a new content in the browser tab. It even changes the tab title dynamically whenever a value in the display name field changes. So nothing to fix here.

But in FF display name disappears from the tab once the content is saved, so that's what we should fix. And yes, it should end with "` / Content Studio`", not "` / Home`".
