### ISSUE TITLE
Incorrect collapse/expand behavior of item-set inside a component config

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#4630]
We have a convenient collapse/expand behaviour of an item-set inside a content type schema (can be tested on [this content type](https://github.com/enonic/app-features/blob/master/src/main/resources/site/content-types/minimum-occurrence-form-item-set/minimum-occurrence-form-item-set.xml) in app-features):

1. A new occurrence of an item-set (or all occurrences in a new content) is always expanded.
2. Existing occurrence of an item-set is by default collapsed.
3. Content Wizard remembers collapse/expand state of each occurrence: if user expands or collapses an occurrence and then saves the content, the occurrences will remain in the same state after save.

Unfortunately, this behaviour doesn't work when item-set is inside a part or layout config (can be tested with [this part](https://github.com/enonic/site-developer/blob/master/src/main/resources/site/parts/panel-items/panel-items.es)): all of the occurrences are always expanded by default. Especially annoying when you collapse some of them, then click "Apply" button and they all get expanded again making you scroll the panel to find where you were.

**Comment by reisfmb** [comment]
@alansemenov 

I was initially looking at the code and couldn't find any problems. Then I started to mess with the content in the part itself and I think I've figured it out... but just to make sure, is there another example of a part in which the problem can be tested? 

The panel items part require all fields (minimum="1") except for the svg icon. If all fields are correctly filled, then after apply or save we'll not get them expanded, which is the correct behavior:

https://user-images.githubusercontent.com/67838246/172440565-8b7d6aa8-ca58-425c-b284-f2af57047ab3.mp4

I suspect that when you were testing, you didn't fill all the required fields for the items, and that's why they were constantly expanded. The problem is that if that's the case, i.e not filling all the required fields, we're not getting any kind of warning as we'd get in the [content type you initially mentioned](https://github.com/enonic/app-features/blob/master/src/main/resources/site/content-types/minimum-occurrence-form-item-set/minimum-occurrence-form-item-set.xml) if we changed some fields to be required:

![image](https://user-images.githubusercontent.com/67838246/172434632-c754c06b-573e-4867-a269-643776619b83.png)

Should we implement some kind of warning / red borders for validation in part config? I tested other parts that not necessarily use item-set and I can see that if we don't fill the required fields we'll also not get any warnings, so maybe that's on purpose.

**Comment by reisfmb** [comment]
@alansemenov 

Btw, I couldn't reproduce this 3rd thing you described: "Content Wizard remembers collapse/expand state of each occurrence: if user expands or collapses an occurrence and then saves the content, the occurrences will remain in the same state after save".

I only get them open / closed, regardless of what state I left them before saving, and that is happening for content types and parts.

**Comment by sigdestad** [comment]
It should be easy to reproduce with the New parts in dev portal. Placing both layouts ans parts on page.

**Comment by alansemenov** [comment]
@reisfmb 

The main problem here is not that we expand/collapse by default depending on required fields, but that we don't preserve state after the form is submitted. Attached is the video that shows that we preserve expanded/collapse state after save in the Content Wizard form. Here I filled out fields inside 3 identical occurrences, then collapsed the 1st and the 3rd one, the 2nd one remained expanded. And they stayed like that after save. We need the same in the Inspect panel.

Here's the form:
```XML
  <form>
    <item-set name="minimum3">
      <label>Minimum 3</label>
      <occurrences minimum="3" maximum="0"/>
      <items>
        <input name="label" type="TextLine">
          <label>Label</label>
          <occurrences minimum="0" maximum="1"/>
        </input>
        <input name="value" type="TextLine">
          <label>Value</label>
          <occurrences minimum="0" maximum="1"/>
        </input>
      </items>
    </item-set>
  </form>
```

https://user-images.githubusercontent.com/11612490/172583959-9ed01275-e7ca-4524-bbde-c39a577c4044.mov

> Should we implement some kind of warning / red borders for validation in part config?

It's a part of bigger task of validating the inspect panel which involves disabling the Apply button for invalid form etc. We will do this at some point, but not now.
