### ISSUE TITLE
Edit page saving can reload the page and loose scrolling position

### ISSUE THREAD

**Issue by poi33** [enonic/app-contentstudio#4738]
When an editor is working on a page with a lot of different components it creates a lot of trouble if they have to find the element they are working on several times when saving. 

If you are working on the last component on a page and save. 
The new reloaded page will have its scroll position at the top. 
The editor will then have to scroll down to the component to see the saved changes. 
Was shown to me with the text component. 
I imagine this is the case with all components that reload the iframe.

**Comment by alansemenov** [comment]
This works fine for other components which have the Apply button in the Inspect panel. When content is saved with the Apply button, selection of a component will be restored after save. Since text component doesn't have the Apply button, it has to be saved with the Save button, and when that is used, selection of a component gets lost.

The bottom line is - no matter how the content is saved (Save button, Cmd-S combination or Apply button), we should behold component selection. Also, if user is inside a text component, we should keep the text component in edit mode and keep the cursor position (like we do in HtmlArea inside Content Wizard).

**Comment by ashklianko** [comment]
I've noticed one more thing: there's no scrolling to the item after applying changes until you open PageComponentsView and expand parent node of a component to make it visible, then you can even close PCV - and scrolling after reload starts working
