### ISSUE TITLE
Content Wizard form collapses after publish

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#547]
1. Open Content Studio (browser window is 1100px, if that matters)
2. Open Superhero for edit
3. Expand widget panel in the Content Wizard. It opens in the floating mode, over the Page Editor - fine.

![image](https://user-images.githubusercontent.com/11612490/59678902-daff5300-91cd-11e9-9006-2d6ede33af3f.png)

4. Publish the site

Bug: After successful publishing the Wizard form for some reason collapses and the widget panel switches to the docked mode

![image](https://user-images.githubusercontent.com/11612490/59679003-0da94b80-91ce-11e9-8f7d-636bd930dcfc.png)

There have been no changes to the browser window. The only thing that happened was content save/publish, which obviously shouldn't have resulted in any panel collapsing or mode switching.

**Comment by alansemenov** [comment]
This issue has reappeared again. Please check and fix.

**Comment by edloidas** [comment]
This issue is currently reproduced for the branch with the Content Layers and no more related to publishing. Reproduce it with the following steps:
1. You need to have a Site in the base layer and the width of the browser of ~1000px;
2. Switch to another layer;
3. Click "Edit local copy" from the Layers widget;
4. In the modal dialog select "Create local copy";
5. In the opened window, the wizard form will collapse.
