### ISSUE TITLE
Research: build d3 graph using actual data model with multi-parent project structure

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#5481]
Post screenshots in comments to this task

**Comment by reisfmb** [comment]
@alansemenov @sigdestad 

### Understanding the underlying data structure

The first thing I did was to understand what is the actual underlying data structure.

I figured out that it is not a **DAG** (directly acyclic graph) which I initially thought it was, it is actually a collections of **trees**, or indeed a **tree** if we consider that the root node is "projects".

A graph can be defined as a tree in the following way:

1. Root Node
2. Directed
3. No cycles
4. Connected
5. Each node must have one parent

Here's why our data structure relates to a **tree**... consider the graph of a single project:

1. Root node exists, in fact it is the project itself;
2. Directed, since each layer has a parent;
3. Acyclic, since we always select a previous created layers or the root project when adding new layers;
4. Connected, since it is mandatory to assign a parent to a new layer;
5. Only one parent, since we always add layers referencing it to a single unique parent.

All of that reasoning implies that we're actually dealing with a collection of trees, where each tree root is one existing project. 

As mentioned before, this can be converted to a tree if we now take the roots of each tree (projects) and consider them the 1st depth nodes of our tree, with "projects" as root. Conclusion, we are dealing with a **tree** structure.

### Visualizing trees 

Now it is a matter of defining how we want to visualize this tree!

Here are some links / screenshots that uses D3 to visualize trees... none of them looked exactly what I have in mind, but since D3 is a very flexible library, my suggestion is to pick one as a starting point and then we continue implementing our tweaks to get to the desired result!

### [Custom Tree of G6](https://observablehq.com/@yanyan-wang/custom-tree-of-g6)
![image](https://user-images.githubusercontent.com/67838246/204950553-eb7500d0-1264-4a4f-bc10-79d2c5d9b386.png)

### [Radial Tree](https://observablehq.com/@d3/radial-tree)
![image](https://user-images.githubusercontent.com/67838246/204950645-ffaa3991-756e-4890-86f0-3f7066a3401e.png)

### [Collapsible Tree](https://observablehq.com/@d3/collapsible-tree)
![image](https://user-images.githubusercontent.com/67838246/204950743-eb372852-6319-46d3-a68d-11df1a45462e.png)

### [Collapsible Vertical Tree](https://observablehq.com/@koljada/collapsible-tree)
![image](https://user-images.githubusercontent.com/67838246/204952118-b0ac2832-8351-413c-a9bd-1f686fc77c91.png)

### [Interactive Tree Diagram (D3v3)](https://observablehq.com/@aaronkyle/interactive-tree-diagram-d3v3)
![image](https://user-images.githubusercontent.com/67838246/204951333-25840c11-2195-4a59-bd13-7b4890f791a1.png)

### [Navigable Nested Tree](https://observablehq.com/@iashishsingh/navigable-nested-tree)
![image](https://user-images.githubusercontent.com/67838246/204951410-d7b4019f-e926-4864-8aae-d3e49041a1e7.png)

Finally, [here](https://observablehq.com/search?query=tree) is the link for further exploration of d3 visualization examples that mention "tree".

**Comment by sigdestad** [comment]
<img width="958" alt="Screenshot 2022-12-01 at 08 48 02" src="https://user-images.githubusercontent.com/482228/204996283-30d54ef4-8161-4ad0-8c35-2720f120c846.png">
Great research Bruno, but seems you have not received a dataset with all relevant information. As I mentioned in the meeting, it is a DAG.  There may be multiple parent nodes for each node. As such, there may also be multiple "root" items, and even dangling nodes (projects that don't have any children) This is why it is a graph, not a tree. See attached sample visualization

**Comment by sigdestad** [comment]
Actually, I forgot one more important fact - if there are multiple parent items, they need to be "weighted" as in show the priority somehow.

New example attached:
![Screenshot 2022-12-01 at 09 16 20](https://user-images.githubusercontent.com/482228/205001351-f0382b61-2f1e-4981-a7c5-82e72e0fbf55.png)

**Comment by sigdestad** [comment]
So, mathematically, I guess there are actually multiple graphs, as each node(set) not connected to others are separate graphs. but they should all be visualized in the same structure.

There will never be cycles in these graphs.

**Comment by reisfmb** [comment]
@sigdestad 

The current data structure I analysed is actually a tree, since layers can only have one parent. But the point of all this is that this is changing... layers will be able to have multiple parents, and therefore, the data structure will change from tree to dag.

Now your images makes sense Thomas, because we'll be allowing multiple parents to layers. Nice!

So I'll look for ways to visualize DAGs with D3 and will post the results of my research here so we can continue discussing them.

**Comment by reisfmb** [comment]
@alansemenov @sigdestad 

I think I found what we need: https://erikbrinkman.github.io/d3-dag/index.html

This is an open source typescript library for rendering directed acyclic graphs using a few different layout methods centered around [layered dag](https://en.wikipedia.org/wiki/Layered_graph_drawing) methodology from [Sugiyama](https://en.wikipedia.org/wiki/Kozo_Sugiyama).

In the following links it is possible to select different data / layout configurations and see the generated visualization:

- https://beta.observablehq.com/@erikbrinkman/d3-dag-sugiyama
- https://beta.observablehq.com/@erikbrinkman/d3-dag-topological

Important to note that d3-dag library is a helper... d3 library is also used to properly generate the svg. The final result is a combination of both.

From my investigations so far d3-dag basically gets the raw data and provides [methods](https://erikbrinkman.github.io/d3-dag/modules.html) to generate a new data structure that will have the right position of nodes (+ some other fancy stuff). From there, the svg generation is done using d3.

I spent some time and without much efforts was able to generate this very simple visualization for this data structure:
```javascript
[
      {
        id: 'project-a',
        parentIds: []
      },
      {
        id: 'layer-a',
        parentIds: ['project-a']
      },
      {
        id: 'project-b',
        parentIds: []
      },
      {
        id: 'layer-b',
        parentIds: ['project-b']
      },
      {
        id: 'layer-c',
        parentIds: ['project-a', 'project-b']
      },
      {
        id: 'layer-d',
        parentIds: ['project-a', 'layer-c']
      },
      {
        id: 'layer-e',
        parentIds: ['project-b', 'layer-d']
      },
      {
        id: 'layer-f',
        parentIds: ['project-a', 'layer-e']
      },
    ]
```
![image](https://user-images.githubusercontent.com/67838246/205188387-25b88c03-0c86-4b39-b622-65f08a0d4640.png)

And here's another visualization using the data @vbradnitski sent:
![image](https://user-images.githubusercontent.com/67838246/205188690-b8cda588-4449-4f02-a817-3a33a34fbf28.png)

**Comment by sigdestad** [comment]
Looks very nice, what about the weighting?

**Comment by alansemenov** [comment]
Looks good. Strange that the "main" [d3 library](https://d3js.org/) doesn't have anything suitable? It's important that the lib we use is a) available on NPM, b) being maintained, c) using a proper license.

**Comment by reisfmb** [comment]
@sigdestad 

Done by code:
![image](https://user-images.githubusercontent.com/67838246/205268752-f6e93776-ef82-4dbc-8b95-abe03cab7d9f.png)

**Comment by reisfmb** [comment]
@alansemenov 

D3 provides a lot of helpers for creating visualizations, but couldn't find anything that would directly help with DAG data structure. Also, d3-dag seems to be the "go to" library when rendering DAG with d3, since a lot of [examples](https://observablehq.com/search?query=dag) that tries to visualize DAG in observablehq uses it

a) https://www.npmjs.com/package/d3-dag

b) 
https://github.com/erikbrinkman/d3-dag/commits/main 
https://github.com/erikbrinkman/d3-dag/tags

c) https://github.com/erikbrinkman/d3-dag/blob/main/LICENSE

**Comment by alansemenov** [comment]
Good to go!

**Comment by sigdestad** [comment]
Looks like we are good to go then. Will ofc need some styling improvements. Each node must be identifiable as a project ofc

**Comment by reisfmb** [comment]
@sigdestad @alansemenov 

Initial design suggestion. Feedbacks?
![image](https://user-images.githubusercontent.com/67838246/205781160-d72aa96a-cc9a-4779-9160-eb699a62b762.png)

**Comment by sigdestad** [comment]
Awesome. We also need the language in () after the displayname. If possible, use a different color on the language
