### ISSUE TITLE
Add visualisation of project structure to the Settings tree

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#5482]
When selecting "Project" folder in the tree, display project structure in a graph inside the right-hand preview panel. Project nodes should be styled in the same way as in the settings tree.

Don't implement navigation as of now.

**Comment by reisfmb** [comment]
@sigdestad @alansemenov 

Here are some previews of the current implementation:

![image](https://user-images.githubusercontent.com/67838246/206103961-e8516c77-0feb-4fdc-93c2-62f47eac325c.png)

![image](https://user-images.githubusercontent.com/67838246/206103658-1a004c9c-e239-4941-a732-75eaa9eaee7d.png)

![image](https://user-images.githubusercontent.com/67838246/206103438-e87c6f27-d90f-414e-80b8-856106c97bbf.png)

@alansemenov I see that you mentioned [here](https://github.com/enonic/app-contentstudio/issues/5482#issue-1468218008) that the nodes should look the same as in the grid, and I tried to do that... you can see that their structure (flag + display name + id) is the same, but I needed to find a way to wrap something around them because of the edges of the graph, so I added that black pill wrapping that structure.

Waiting for feedbacks to keep improving the design and implementing new features.

**Comment by alansemenov** [comment]
Looking good, Bruno! It's now a matter of a simple CSS tweak to make the nodes look like in the tree - just remove the color fill and keep a thin border.

Personally, I don't see much point in showing weight - these numbers are very confusing and we don't really have a concept of weight, we only have "main" parent and the rest. What we could do is have a thick line between a layer and its main parent and normal/thin lines between the layer and the rest of the parents.
