### ISSUE TITLE
IssueDetailsDialog - Publish button should be enabled in the dialog

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#7001]
1. Select `Superhero` site , create new issue.
2. Go to `Items` tab in  ` Issue Deatils Dialog`

Issue - `Publish` button should be enabled even if there invalid or work in progress dependent items.

![image](https://github.com/enonic/app-contentstudio/assets/3728712/dee1c3f3-d9dd-4f91-b6d1-31532ca9bd89)

**Comment by edloidas** [comment]
So we have an IssueDetails dialogue that displays an issue differently depending on whether it is a normal issue or a publish request.
From our official documentation we can see that the actual difference is only in the flag that changes the whole publishing process:
_This dialogue is somewhat similar to the Issue dialogue. The main difference is that content items are displayed on the first tab and can be published directly from this dialogue with "Publish Now" button.
In general, let's consider three variants of the dialogue: Publish, Issue Details, Request Publish._

**Publish**
The main difference is the status bar, which shows that the content is ready for publication, or shows errors and gives the opportunity to correct them. Everything is very logical: we work with the content we have chosen, and by performing an action (publishing) we finish the work.

**Issue Details**
The status bar disappears and a selector appears to select new content. Everything is kind of logical too. Issue is a kind of tasks that users work on, leave requests, comments, group content under these tasks. Publishing content and making it ready for publication doesn't seem to be the main goal. BUT, clicking publish takes me to the Publish Dialog. And there I can select completely different content: I can delete it, replace dependencies. The weird thing is that if the main content is all pablised, I can select just one dependency (and a completely different one, which was excluded in Issue details), and publish it alone. And the Issue will close automatically. Question: why? And the content in the issue will not change.

**Request Publish**
This is really just an attempt to speed up the publishing process. In fact, the difference is only in the flag by which you can filter content in Issues and in the Tab order in the dialogue. Although content can be published from the dialogue itself, we don't have a content status panel and the ability to exclude and prepare content. It's a chimera that tries to be both one and two dialogues, but does it badly. At least since the introduction of Apply Selection.
We need to unify the Issue Details and Requet Publish dialogues by developing one approach. In fact, given the problems described above with Issue Details, I'd suggest giving the option to publish immediately, as well as adding a content status line.

I would suggest to minimize the differences in the last two dialogs (and in fact in one, in different states) so that users understand that this is an issue, and this is the same issue, but of the subtype (with the label) request publish, i.e. the administrator does not want edits and content checks to be made, but content to be published.

**Comment by edloidas** [comment]
Won't fix. Must be an improvement in a separate issue.
