### ISSUE TITLE
Content should remain in state "Ready" after page component(s) were saved as fragment

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#787]
1. Open Features(Ready for Publishing)
2. Open Page Component View and click on the text component and select `Save as Fragment`

BUG: The site gets Work in Progress after saving the fragment.
![image](https://user-images.githubusercontent.com/3728712/63029154-ba473700-beb8-11e9-9371-030dbbc07743.png)

**Comment by alansemenov** [comment]
1. If some other changes are made to the content (without save) and then a fragment is created, then the content should be "In progress", because content itself was changed. Now it will always mark as ready whenever a fragment is created. Basically, we have to check content state at the moment a fragment is created. If the content is already in progress, then don't mark as ready.

2. When a fragment is disassembled (with "Detach from fragment" action in the context menu), there should be the same logic as when creating a fragment. Now content will always go to "In progress".
