### ISSUE TITLE
Differrent behaviour of Preview button when shortcut is selected

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#8116]
What should be displayed in the preview panel, when a shortcut with different types of target is selected? 

1, Create a shortcut, select a site(Features) in its target
2. Select the shortcut in the Browse Panel - The site appears in `Automatic` preview , `Preview` button is **enabled**

![image](https://github.com/user-attachments/assets/b40559ba-6026-4ad1-9b4e-182d039780d3)

3. Change the target in the site, (select an image )

**Issue** - image is not displayed in the  `Automatic` preview 
![image](https://github.com/user-attachments/assets/879dbbb1-eb85-425a-9510-8b0d002f0bd4)

5. Change the target again - select a `text-content` 

**Issue** - the text is not displayed in the preview 

![image](https://github.com/user-attachments/assets/340c1560-0392-4780-af32-2e14c1d0133d)

**Comment by pmi** [comment]
This one is a bit tricky, because only the Site Engine is able to follow shortcuts at the same time Site Engine is unable to render media.
Similarly media widget is able to render media, but unable to follow shortcuts.
@alansemenov Should we enable media widget to follow shortcuts to media similar to how Site engine does it?

Automatic widget in it's turn just shows first widget that is capable of rendering a content. And in the case with shortcut to image none of the widgets is able to render it which gives you following message:

![Image](https://github.com/user-attachments/assets/7ccf72f0-af73-4c49-b50b-3108429960b6)

**Comment by pmi** [comment]
Discussed with @alansemenov, this is correct behavior.

**Comment by pmi** [comment]
@sgauruseu found a [bug about that](https://github.com/enonic/app-contentstudio/issues/4294) 

So we are going to hide previews for any shortcut
