### ISSUE TITLE
Content state changes from Ready to In progress after text component switches to edit mode

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#827]
1. Install the Features app
2. Open the Features site for edit (it should by default be in Ready state after import, if not - mark it as ready). 
3. Hover cursor over "Hello world" text component in the Page Editor and double-click it

The component switches to edit mode. Save button becomes enabled and state of the content changes from "Ready" to "In progress" even though no changes have been made yet.

**Comment by pmi** [comment]
This happens for the first time edit of the text component that was not created manually (i.e. was imported) only. 
The reason for that is that text editor changes component value from `Hello world!` --> `<p>Hello world!</p>↵` which is absolutely ok since it is a rich text editor.
All subsequent edits as well as components created manually in page editor do not change publish state.
