### ISSUE TITLE
Synchronise refresh of state icons in the Content Wizard

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-contentstudio#843]
The default action "unpublish" is correct, but the state should not be "in progress"? It should not have any state at this moment.

![Screenshot 2019-08-27 at 13 57 35](https://user-images.githubusercontent.com/482228/63769419-0f307780-c8d3-11e9-9e43-da22a1df2ab2.png)

**Comment by edloidas** [comment]
@sigdestad Are there any special steps to reproduce this? Nor I, nor @sgauruseu can't reproduce this. A similar issue was [fixed](#792) several days ago.

**Comment by sgauruseu** [comment]
the similar issue was fixed : https://github.com/enonic/app-contentstudio/issues/792

**Comment by alansemenov** [comment]
This is a different thing. It was never implemented because we never discussed it. 

Basically, when content is "Unpublished" AND workflow state is "Ready", we should hide the state icon, just like when do when it's "Published". But if it's "Unpublished" and workflow state is "In progress", then it means that someone changed content after unpublishing and then the icon should be shown.

**Comment by alansemenov** [comment]
@edloidas Can we have a more robust solution for this? If it happens randomly then it most likely depends on the pc performance. But we should have the same logic for update of the state icon in the content wizard form and inside the wizard toolbar. They must always update together, also visually.
